/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubeconfigArgumentInjectable from "./kubeconfig-argument.injectable";
import openKubeconfigInjectable from "./open-kubeconfig.injectable";
import openKubeconfigOfFirstInstanceInjectable from "./open-kubeconfig-of-first-instance.injectable";
import openKubeconfigOfSecondInstanceInjectable from "./open-kubeconfig-of-second-instance.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubeconfigArgumentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openKubeconfigOfFirstInstanceInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openKubeconfigOfSecondInstanceInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
