/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import handleOpenKubeconfigUrlInjectable from "./handle-open-kubeconfig-url.injectable";
import openClusterOfKubeconfigInjectable from "./open-cluster-of-kubeconfig.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(handleOpenKubeconfigUrlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openClusterOfKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
